[workspace]
members = ["contracts/*", "bot"]
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
cw-orch = "0.20.1"

cosmwasm-std = { version = "1.5" }

abstract-app = { version = "0.21.0" }
abstract-interface = { version = "0.21.0" }
abstract-dex-adapter = { git = "https://github.com/abstractsdk/abstract.git" }
abstract-money-market-adapter = { git = "https://github.com/abstractsdk/abstract.git" }
abstract-money-market-standard = { git = "https://github.com/abstractsdk/abstract.git" }
abstract-client = { version = "0.21.0" }
abstract-testing = { version = "0.21.0" }
abstract-sdk = { version = "0.21.0", features = ["stargate"] }


[patch.crates-io]
# This is included to avoid recompling too much
osmosis-test-tube = { path = "../test-tube/packages/osmosis-test-tube" }


# This was added to account for the fix data forwaring in the proxy contract + moneymarket adapter
abstract-app = { git = "https://github.com/abstractsdk/abstract.git" }
abstract-adapter = { git = "https://github.com/abstractsdk/abstract.git" }
abstract-adapter-utils = { git = "https://github.com/abstractsdk/abstract.git" }
abstract-interface = { git = "https://github.com/abstractsdk/abstract.git" }
abstract-client = { git = "https://github.com/abstractsdk/abstract.git" }
abstract-testing = { git = "https://github.com/abstractsdk/abstract.git" }
abstract-core = { git = "https://github.com/abstractsdk/abstract.git" }
abstract-sdk = { git = "https://github.com/abstractsdk/abstract.git" }


[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
