[workspace]
members = ["contracts/*", "bot"]
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
cw-orch = "0.20.0"

[patch.crates-io]
abstract-adapter = { git = "https://github.com/abstractsdk/abstract", branch = "bump/cw-orch" }
abstract-adapter-utils = { git = "https://github.com/abstractsdk/abstract", branch = "bump/cw-orch" }
abstract-interface = { git = "https://github.com/abstractsdk/abstract", branch = "bump/cw-orch" }
abstract-core = { git = "https://github.com/abstractsdk/abstract", branch = "bump/cw-orch" }
abstract-dex-standard = { git = "https://github.com/abstractsdk/abstract", branch = "bump/cw-orch" }
abstract-staking-standard = { git = "https://github.com/abstractsdk/abstract", branch = "bump/cw-orch" }
abstract-sdk = { git = "https://github.com/abstractsdk/abstract", branch = "bump/cw-orch" }
