[workspace]
members = [
    "contracts/*",
     "savings-bot"
]
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
cw-orch = "0.20.0"
abstract-app = { version = "0.20.0" }
abstract-interface = { version = "0.20.0" }

abstract-dex-adapter = { git = "https://github.com/abstractsdk/abstract.git", branch = "bump/cw-orch-bech32" }

[patch.crates-io]
abstract-app = { git = "https://github.com/abstractsdk/abstract.git", branch = "bump/cw-orch-bech32" }
abstract-adapter = { git = "https://github.com/abstractsdk/abstract.git", branch = "bump/cw-orch-bech32" }
abstract-adapter-utils = { git = "https://github.com/abstractsdk/abstract.git", branch = "bump/cw-orch-bech32" }
abstract-interface = { git = "https://github.com/abstractsdk/abstract.git", branch = "bump/cw-orch-bech32" }
abstract-core = { git = "https://github.com/abstractsdk/abstract.git", branch = "bump/cw-orch-bech32" }
abstract-dex-standard = { git = "https://github.com/abstractsdk/abstract.git", branch = "bump/cw-orch-bech32" }
abstract-staking-standard = { git = "https://github.com/abstractsdk/abstract.git", branch = "bump/cw-orch-bech32" }
abstract-sdk = { git = "https://github.com/abstractsdk/abstract.git", branch = "bump/cw-orch-bech32" }

# abstract-adapter = { path = "../abstract/framework/packages/abstract-adapter" }
# abstract-adapter-utils = { path = "../abstract/framework/packages/standards/utils" }
# abstract-interface = { path = "../abstract/framework/packages/abstract-interface" }
# abstract-core = { path = "../abstract/framework/packages/abstract-core" }
# abstract-dex-standard = { path = "../abstract/framework/packages/standards/dex" }
# abstract-staking-standard = { path = "../abstract/framework/packages/standards/staking" }
# abstract-sdk = { path = "../abstract/framework/packages/abstract-sdk" }

cw-orch = { git = "https://github.com/abstractsdk/cw-orchestrator", branch = "fix/checksum-should-not-be-string" }

# [patch."https://github.com/abstractsdk/abstract"]
# abstract-adapter = { path = "../abstract/framework/packages/abstract-adapter" }
# abstract-client = { path = "../abstract/framework/packages/abstract-client" }
# abstract-adapter-utils = { path = "../abstract/framework/packages/standards/utils" }
# abstract-interface = { path = "../abstract/framework/packages/abstract-interface" }
# abstract-core = { path = "../abstract/framework/packages/abstract-core" }
# abstract-dex-standard = { path = "../abstract/framework/packages/standards/dex" }
# abstract-staking-standard = { path = "../abstract/framework/packages/standards/staking" }
# abstract-sdk = { path = "../abstract/framework/packages/abstract-sdk" }
